name: build
on:
  push:
    branches:
      - master
jobs:
  hello-actions:
    runs-on: ubuntu-18.04
    name: hello-actions
    steps:
      # 每一个不走步骤跟随一个 name ，还有一些其他的参数。
      - name: Checkout Master
        uses: actions/checkout@v1

      - name: run deploy
        run: npm run deploy
